package utils.datetime;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;

/**
 * Utility class for date and time operations with formatted string handling.
 * 
 * <h2>Key Features:</h2>
 * <ul>
 *   <li><strong>Formatted Time:</strong> Get current time in "yyyy-MM-dd HH:mm:ss" format</li>
 *   <li><strong>Format Validation:</strong> Detect if a string matches the expected datetime format</li>
 *   <li><strong>User Input Detection:</strong> Determine if a timestamp was generated by program or modified by user</li>
 * </ul>
 * 
 * <h2>Usage Examples:</h2>
 * 
 * <h3>Get Current Timestamp:</h3>
 * <pre>
 * DateTimeOperator operator = new DateTimeOperator();
 * String now = operator.getCurrentTime();
 * // Result: "2023-12-02 14:35:20"
 * </pre>
 * 
 * <h3>Validate Format (Check if User Modified):</h3>
 * <pre>
 * DateTimeOperator operator = new DateTimeOperator();
 * 
 * // Program-generated format
 * String validFormat = "2023-12-02 14:35:20";
 * boolean isGenerated1 = operator.isStillUseProgramGeneratedString(validFormat);
 * // Result: true (matches expected format)
 * 
 * // User-modified or invalid format
 * String userModified = "2023/12/02 2:35 PM";
 * boolean isGenerated2 = operator.isStillUseProgramGeneratedString(userModified);
 * // Result: false (doesn't match expected format)
 * </pre>
 * 
 * <h2>Use Cases:</h2>
 * <ul>
 *   <li>Generate timestamps for log files and analysis results</li>
 *   <li>Detect if user manually edited a timestamp field</li>
 *   <li>Validate datetime string format before processing</li>
 *   <li>Track analysis execution times</li>
 * </ul>
 * 
 * <h2>Format Specification:</h2>
 * <p>Uses the fixed format pattern: <code>yyyy-MM-dd HH:mm:ss</code></p>
 * <ul>
 *   <li>yyyy: 4-digit year</li>
 *   <li>MM: 2-digit month (01-12)</li>
 *   <li>dd: 2-digit day (01-31)</li>
 *   <li>HH: 2-digit hour in 24-hour format (00-23)</li>
 *   <li>mm: 2-digit minute (00-59)</li>
 *   <li>ss: 2-digit second (00-59)</li>
 * </ul>
 * 
 * @author yudalang
 * @since 1.0
 */
public class DateTimeOperator {

    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");


    public String getCurrentTime() {
        LocalDateTime now = LocalDateTime.now();
        String formatted = now.format(formatter);
        return formatted;
    }

    public boolean isStillUseProgramGeneratedString(String isUserEnteredStr) {
        boolean isEnter = true;
        try  {
            TemporalAccessor parse = formatter.parse(isUserEnteredStr);
        } catch (Exception e) {
            //  这里忽略异常，用异常来判断是否 要更新(不能解析说明用户改过了)
            isEnter = false;
        }
        return isEnter;
    }
}
